apiVersion: v1
kind: Secret
metadata:
  name: nodejs-app-secret
type: Opaque
data:
  MONGO_URI: "bW9uZ29kYitzcnY6Ly96aXpvbzE1NjZfZGI6NWt2UDZaRHdmWXYwNTBEakBjbHVzdGVyMC5rOHZxYjdzLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA=="
