---
- name: Disable the UFW firewall
  community.general.ufw:
    state: disabled

- name: Ensure br_netfilter module is loaded
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Set kernel parameters for K3s networking
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    state: present
    reload: yes

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common packages
  ansible.builtin.apt:
    name:
      - curl
      - vim
      - git
      - socat
    state: present

- name: Kill any existing node_exporter process to free up port 9100
  ansible.builtin.shell: "pkill node_exporter || true"
  changed_when: false
