---
- name: "MASTER | 1. Reset existing cluster state if any"
  command: kubeadm reset -f
  ignore_errors: true

- name: "MASTER | 2. Initialize the Kubernetes cluster using kubeadm"
  command: >
    kubeadm init
    --pod-network-cidr=192.168.0.0/16
    --apiserver-advertise-address={{ ansible_default_ipv4.address }}
    --upload-certs
  register: kubeadm_init_result

- name: "MASTER | 3. Create .kube directory for the user"
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: "MASTER | 4. Copy admin.conf to user's .kube directory"
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"

- name: "MASTER | 5. Install Calico CNI"
  command: "kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml"
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

- name: "MASTER | 6. Generate a new worker join token and command"
  command: kubeadm token create --print-join-command
  register: kubeadm_join_command_result

- name: "MASTER | 7. Store the join command for worker nodes to use"
  set_fact:
    join_command: "{{ kubeadm_join_command_result.stdout }}"
    cacheable: true
