apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: 'kube-prometheus-stack'
    targetRevision: '45.28.0'
    helm:
      values: |
        crds:
          enabled: false
        prometheus-node-exporter:
          affinity: {}
        prometheus:
          prometheusSpec:
            affinity: {}
        alertmanager:
          alertmanagerSpec:
            affinity: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true