apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    chart: "kube-prometheus-stack"
    targetRevision: "58.2.1"
    helm:
      # This 'values' block contains the fix
      values: |
        # This is the fix for the Pending pods
        prometheus-node-exporter:
          affinity: {}
        kube-state-metrics:
          affinity: {}
        # The rest of the values remain to try and disable other components
        crds:
          enabled: true
        alertmanager:
          enabled: false
        grafana:
          enabled: false
        prometheus:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
