# kubernetes/apps/nodejs-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ztr1566/k3s-node-project.git'
    targetRevision: HEAD
    path: kubernetes/manifests/
  destination:
    server: https://kubernetes.default.svc
    namespace: nodejs-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true