---
- name: Check if K3s agent service is active
  ansible.builtin.command: systemctl is-active k3s-agent.service
  register: k3s_agent_status
  changed_when: false
  failed_when: false

- name: Run uninstall script if K3s agent is not active
  ansible.builtin.command: /usr/local/bin/k3s-agent-uninstall.sh
  ignore_errors: true
  changed_when: false
  when: k3s_agent_status.rc != 0

- name: Install K3s on Worker nodes if agent was not active
  ansible.builtin.shell:
    cmd: >
      curl -sfL https://get.k3s.io |
      K3S_URL=https://{{ groups['master'][0] }}:6443
      K3S_TOKEN={{ hostvars[groups['master'][0]]['k3s_token_output'].stdout }}
      INSTALL_K3S_EXEC="--docker"
      sh -
  when: k3s_agent_status.rc != 0